language: python
python: 3.6
branches: master
install:
- pip install mkdocs mkdocs-material pymdown-extensions pygments
script: true
before_deploy:
- mkdocs build --verbose --clean
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: site
  on:
    branch: master