site_name: Meu Brechó
pages:
  - Home: 'index.md'
  - Base: 
    - Módulo Projeto Não Orientado a Abordagens Específicas:
      - 5W2H: 'base/5W2H.md'
      - Diagrama causa-efeito: 'base/causa-efeito.md'
      - Esforço e Tempo: 'base/esforco-tempo.md'
      - Custo: 'base/custo.md'
      - Plano de Riscos: 'base/risco.md'
      - Elicitação: 
        - Brainstorming: 'base/elicitacao/Brainstorming.md'
        - Questionário: 'base/elicitacao/Questionario.md'
      - Design Sprint: 'base/designSprint.md'
      - Mapa Mental: 'base/mapamental.md'
      - Rich Picture: 'base/richpicture.md'
      - Protótipo de Alta Fidelidade: "base/prototipo.md"
    - Módulo Processos/Metodologias/Abordagens:
      - BPMN: 'base/bpmn.md'
      - Metodologia: 'base/metodologia.md'
  - Modelagem:
    - Diagrama Dinâmicos:
      - Diagrama de Atividades: 'modelagem/dinamicos/diagramaAtividades.md'
      - Diagrama de Sequências: 'modelagem/dinamicos/diagramaSequencia.md'
      - Diagrama de Comunicação: 'modelagem/dinamicos/diagramaComunicacao.md'
      - Diagrama de Estados: 'modelagem/dinamicos/diagramaEstado.md'
      - Diagrama de Casos de Uso: 'modelagem/dinamicos/diagramacasoUso'
    - Diagrama Estáticos:
      - Diagrama de Classes: 'modelagem/estaticos/diagramaClasses.md'
      - Diagrama de Pacotes: 'modelagem/estaticos/diagramaPacotes.md'
      - Diagrama de Componentes: 'modelagem/estaticos/diagramaComponentes'
    - Modelagem: 
      - Product Backlog: 'base/elicitacao/priorizacao/Moscow.md'
    - Iniciativas Extras:
      - DER Diagrama Entidade-Relacionamento: 'modelagem/diagramaDER'
  - Padrões de projeto:
      - GRASPs: 
        - Controllers: 'padroes_projeto/GRASPs/controllers.md'
        - Especialista: 'padroes_projeto/GRASPs/especialista.md'
        - Polimorfismo: 'padroes_projeto/GRASPs/polimorfismo.md'
      - GoFs:
        - Criacionais:
          - Factory Method: 'padroes_projeto/GoFs/criacionais/factory_method.md'
          - Sigleton: 'padroes_projeto/GoFs/criacionais/sigleton.md'
        - Estruturais:
          - Composite: 'padroes_projeto/GoFs/estruturais/composite.md'
          - Facade: 'padroes_projeto/GoFs/estruturais/facade.md'
        - Comportamentais:
          - Memento: 'padroes_projeto/GoFs/comportamentais/memento.md'
          - State: 'padroes_projeto/GoFs/comportamentais/state.md'
      - Padrões Extras:
        - Service Layer Pattern:  'padroes_projeto/extras/service.md'
            
          
theme:
  name: material
  language: pt

repo_name: 'Repositório'
repo_url: 'https://github.com/UnBArqDsw2020-2/2020.2_G4'
